# Generated by Django 5.2.7 on 2025-10-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_certificado', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=200)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('ruta_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('ruta_qr', models.CharField(blank=True, max_length=255, null=True)),
                ('url_verificacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
